Artapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
]

Artapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django_resized import ResizedImageField

class CustomUserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(unique=True)
    user_type = models.CharField(max_length=10)

    # Required fields for AbstractBaseUser
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(auto_now=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'user_type']

    groups = models.ManyToManyField(
        'auth.Group',
        blank=True,
        related_name='artapp_user_groups',
        related_query_name='user'
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        blank=True,
        related_name='artapp_user_permissions',
        related_query_name='user'
    )
    
    def __str__(self):
        return self.username


class Seller(models.Model):
    totalSales = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    successAuctions = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=100)
    image = ResizedImageField(size=[300, 300], crop=['middle', 'center'])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Artwork(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    aimg = ResizedImageField(size=[262, 280], default='/static/img/default-artwork.jpg')
    Description = models.TextField()
    creationDate = models.DateField()
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, related_name='artworks_seller')
    artworkStatus = models.BooleanField(null=False, default=True)
    width = models.FloatField(default=0.0)
    height = models.FloatField(default=0.0)
    frame = models.CharField(max_length=30, default='No')
    condition = models.CharField(max_length=50, default='Good')
    def __str__(self):
        return self.title

class Buyer(models.Model):
    favourites = models.ForeignKey(Artwork, on_delete=models.CASCADE, null=True)
    totalBids = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username

class Auction(models.Model):
    artwork = models.ForeignKey(Artwork, on_delete=models.CASCADE)
    startDate = models.DateTimeField()
    endDate = models.DateTimeField()
    basePrice = models.DecimalField(max_digits=10, decimal_places=2)
    auctionStatus = models.BooleanField()
    winner=models.ForeignKey(Buyer, on_delete=models.CASCADE, null=True)
    


class Bid(models.Model):
    buyer = models.ForeignKey(Buyer, on_delete=models.CASCADE, related_name='bids_buyer')
    artwork = models.ForeignKey(Artwork, on_delete=models.CASCADE)
    bidAmount = models.DecimalField(max_digits=10, decimal_places=2)


class Comment(models.Model):
    artwork = models.ForeignKey(Artwork, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    commentText = models.TextField()
    datePosted = models.DateTimeField()

Artapp/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ['username', 'password1', 'password2']
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

templates/addArtwork.html
{% extends 'masterSeller.html' %}
{% block body %}
		<!-- Start Banner Area -->
		<section class="banner-area organic-breadcrumb">
			<div class="container">
				<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
					<div class="col-first">
						<h1>Add Artwork</h1>
						<nav class="d-flex align-items-center">
							<a href="{% url 'indexSeller' %}">Home<span class="lnr lnr-arrow-right"></span></a>
						</nav>
					</div>
				</div>
			</div>
		</section>
		<!-- End Banner Area -->
	
		<!--================Login Box Area =================-->
		<section class="login_box_area section_gap">
			<div class="container">
				<div class="row">
					<div class="col-lg-6">
						<div class="login_box_img">
							<img class="img-fluid" src="/static/img/addArtwork.jpg" alt="">
							<div class="hover">
								<h4>Add New Artwork</h4>
							</div>
						</div>
					</div>
					<div class="col-lg-6">
						<div class="login_form_inner">
							<h3>Add Artwork</h3>
							<form class="row login_form" action="{% url 'addArt' %}" method="POST" enctype="multipart/form-data">
								{% csrf_token %}
								<div class="col-md-12 form-group">
									<input type="text" class="form-control" name="title" placeholder="Artwork Title" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Artwork Title'">
								</div>
                                    <input style="margin-left:20px;" type="file" id="artworkImage" name="artworkImage" accept="image/*" ><br><br>
                                <div class="col-md-12 form-group">
									<input type="text" class="form-control" name="description" placeholder="Artwork Description" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Artwork Description'">
								</div>
                                <div class="col-md-12 form-group">
                                    <select name="category" required id="id_category">
                                        {% for c in categories %}
                                            <option value="{{c.name}}">{{c.name}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <input style="margin-left:20px;margin-bottom:20px;" type="date" id="cDate" name="cDate">
                                <div class="col-md-12 form-group">
									<input type="number" class="form-control" name="width" placeholder="Artwork Width(in inch)" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Artwork Width(in inch)'">
								</div>
                                <div class="col-md-12 form-group">
									<input type="number" class="form-control" name="height" placeholder="Artwork Height(in inch)" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Artwork Height(in inch)'">
								</div>
                                <div class="col-md-12 form-group">
									<input type="text" class="form-control" name="frame" placeholder="Artwork Frame(if any)" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Artwork Frame(if any)'">
								</div>
                                <div class="col-md-12 form-group">
									<input type="text" class="form-control" name="condition" placeholder="Artwork Condition" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Artwork Condition'">
								</div>
								<div class="col-md-12 form-group">
									<button type="submit" value="submit" class="primary-btn">Auction</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--================End Login Box Area =================-->
{% endblock %}

templates/artworkDetail.html
{% extends 'master.html' %}
{% block body %}
    <!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>{{artworkDetail.title}}</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'index' %}">Home<span class="lnr lnr-arrow-right"></span></a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

    	<!--================Single Product Area =================-->
	<div class="product_image_area">
		<div class="container">
			<div class="row s_product_inner">
				<div class="col-lg-6">
                    <div class="single-prd-item" style="margin-left:100px;">
                        <img class="img-fluid" src="{{ artworkDetail.aimg.url }}" alt="">
                    </div>
				</div>
				<div class="col-lg-5 offset-lg-1">
					<div class="s_product_text">
						<h3>{{artworkDetail.title}}</h3>
						<h2>₹{{auctionDetail.basePrice}}</h2>
						<ul class="list">
							<li><span>Category</span> : {{artworkDetail.category}}</a></li>
							<li><span>Availibility</span> : {% if artworkDetail.artworkStatus %} Available
							{% else %}
								Sold
							{% endif %}</li>
						</ul>
						<br>
						<h6>Closing date : {{auctionDetail.endDate}}</h6>
						<br><br>
						{% if artworkDetail.artworkStatus == False %}
						<h6>Winner : {{ auctionDetail.winner.user.username }}</h6>
						{% endif %}
						<div class="card_area d-flex align-items-center">
							<a class="primary-btn" href="{% url 'bidArt' id=artworkDetail.id %}">Bid</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--================End Single Product Area =================-->
	<section class="product_description_area">
		<div class="container">
			<ul class="nav nav-tabs" id="myTab" role="tablist">
				<li class="nav-item">
					<a class="nav-link" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Description</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile"
					 aria-selected="false">Specification</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact"
					 aria-selected="false">Comments</a>
				</li>
			</ul>
			<div class="tab-content" id="myTabContent">
				<div class="tab-pane fade" id="home" role="tabpanel" aria-labelledby="home-tab">
					<p>{{artworkDetail.Description}}</p>
				</div>
				<div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
					<div class="table-responsive">
						<table class="table">
							<tbody>
								<tr>
									<td>
										<h5>Width</h5>
									</td>
									<td>
										<h5>{{artworkDetail.width}}"</h5>
									</td>
								</tr>
								<tr>
									<td>
										<h5>Height</h5>
									</td>
									<td>
										<h5>{{artworkDetail.height}}"</h5>
									</td>
								</tr>
								<tr>
									<td>
										<h5>Frame</h5>
									</td>
									<td>
										<h5>{{artworkDetail.frame}}</h5>
									</td>
								</tr>
								<tr>
									<td>
										<h5>Condition</h5>
									</td>
									<td>
										<h5>{{artworkDetail.condition}}</h5>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
					<div class="row">
						<div class="col-lg-6">
							<div class="comment_list">
                                {% for comment in commentDetails %}
                                <div class="review_item">
                                    <div class="media">
                                        <div class="d-flex">
                                            <img src="img/product/review-1.png" alt="">
                                        </div>
                                        <div class="media-body">
                                            <h4>{{comment.user.username}}</h4>
                                            <h5>{{comment.datePosted}}</h5>
                                        </div>
                                    </div>
                                    <p>{{comment.commentText}}</p>
                                </div>
                                {% endfor %}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="review_box">
								<h4>Post a comment</h4>
								<form class="row contact_form" action="{% url 'artworkDetail' id=artworkDetail.id %}" method="post">
									{% csrf_token %}
									<div class="col-md-12">
										<div class="form-group">
											<textarea class="form-control" name="message" placeholder="Message"></textarea>
										</div>
									</div>
									<div class="col-md-12 text-right">
										<button type="submit" value="submit" class="btn primary-btn">POST</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/artworkDetailSeller.html
{% extends 'masterSeller.html' %}
{% block body %}
    <!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>{{artworkDetail.title}}</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'indexSeller' %}">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="{% url 'viewAllArtSeller' %}">My Artworks</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

    	<!--================Single Product Area =================-->
	<div class="product_image_area">
		<div class="container">
			<div class="row s_product_inner">
				<div class="col-lg-6">
                    <div class="single-prd-item" style="margin-left:100px;">
                        <img class="img-fluid" src="{{ artworkDetail.aimg.url }}" alt="">
                    </div>
				</div>
				<div class="col-lg-5 offset-lg-1">
					<div class="s_product_text">
						<h3>{{artworkDetail.title}}</h3>
						<h2>₹{{auctionDetail.basePrice}}</h2>
						<ul class="list">
							<li><span>Category</span> : {{artworkDetail.category}}</a></li>
							<li><span>Availibility</span> : {% if artworkDetail.artworkStatus %} Available
							{% else %}
								Sold
							{% endif %}</li>
						</ul>
						<br>
						<h6>Closing date : {{auctionDetail.endDate}}</h6>
						<br><br>
						{% if artworkDetail.artworkStatus == False %}
						<h6>Winner : {{ auctionDetail.winner.user.username }}</h6>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--================End Single Product Area =================-->
	<section class="product_description_area">
		<div class="container">
			<ul class="nav nav-tabs" id="myTab" role="tablist">
				<li class="nav-item">
					<a class="nav-link" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Description</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile"
					 aria-selected="false">Specification</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact"
					 aria-selected="false">Comments</a>
				</li>
			</ul>
			<div class="tab-content" id="myTabContent">
				<div class="tab-pane fade" id="home" role="tabpanel" aria-labelledby="home-tab">
					<p>{{artworkDetail.Description}}</p>
				</div>
				<div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
					<div class="table-responsive">
						<table class="table">
							<tbody>
								<tr>
									<td>
										<h5>Width</h5>
									</td>
									<td>
										<h5>{{artworkDetail.width}}"</h5>
									</td>
								</tr>
								<tr>
									<td>
										<h5>Height</h5>
									</td>
									<td>
										<h5>{{artworkDetail.height}}"</h5>
									</td>
								</tr>
								<tr>
									<td>
										<h5>Frame</h5>
									</td>
									<td>
										<h5>{{artworkDetail.frame}}</h5>
									</td>
								</tr>
								<tr>
									<td>
										<h5>Condition</h5>
									</td>
									<td>
										<h5>{{artworkDetail.condition}}</h5>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
					<div class="row">
						<div class="col-lg-6">
							<div class="comment_list">
                                {% for comment in commentDetails %}
                                <div class="review_item">
                                    <div class="media">
                                        <div class="d-flex">
                                            <img src="img/product/review-1.png" alt="">
                                        </div>
                                        <div class="media-body">
                                            <h4>{{comment.user.username}}</h4>
                                            <h5>{{comment.datePosted}}</h5>
                                        </div>
                                    </div>
                                    <p>{{comment.commentText}}</p>
                                </div>
                                {% endfor %}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="review_box">
								<h4>Post a comment</h4>
								<form class="row contact_form" action="{% url 'artworkDetailSeller' id=artworkDetail.id %}" method="post">
									{% csrf_token %}
									<div class="col-md-12">
										<div class="form-group">
											<textarea class="form-control" name="message" placeholder="Message"></textarea>
										</div>
									</div>
									<div class="col-md-12 text-right">
										<button type="submit" value="submit" class="btn primary-btn">POST</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/auctionForm.html
{% extends 'master.html' %}
{% block body %}
    	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Auction the Artwork</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'indexSeller' %}">Home<span class="lnr lnr-arrow-right"></span></a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

        <!--================Login Box Area =================-->
		<section class="login_box_area section_gap">
			<div class="container">
				<div class="row">
					<div class="col-lg-6">
						<div class="login_box_img">
							<img class="img-fluid" src="/static/img/auction-form.jpg" alt="">
							<div class="hover">
								<h4>Auction Artwork</h4>
							</div>
						</div>
					</div>
					<div class="col-lg-6">
						<div class="login_form_inner">
							<h3>Aution Artwork</h3>
							<form class="row login_form" action="{% url 'auctionArt' id=artwork.id %}" method="POST">
								{% csrf_token %}
                                <div class="col-md-12 form-group">
                                    Start Date :
                                    <input style="margin-left:20px;margin-bottom:20px;" type="date" id="sDate" name="sDate">
                                </div>
                                <div class="col-md-12 form-group">
                                    End Date :
                                    <input style="margin-left:20px;margin-bottom:20px;" type="date" id="eDate" name="eDate">
                                </div>
								<div class="col-md-12 form-group">
									<input type="number" class="form-control" name="basePrice" placeholder="Base Price" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Base Price'">
								</div>
								<div class="col-md-12 form-group">
									<button type="submit" value="submit" class="primary-btn">Auction</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</section>
	<!--================End Login Box Area =================-->
    <br><br><br>
{% endblock %}

templates/auctionResult.html
{% extends 'master.html' %}
{% block body %}
    <!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Auction Result</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'index' %}">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="#">Auction Result</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->
        <!--================Blog Area =================-->
        <section class="blog_area single-post-area section_gap">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 posts-list">
                        <div class="single-post row">
                            <div class="col-lg-12">
                                <div class="feature-img">
                                    <img class="img-fluid" src="{{ artwork.aimg.url }}" alt="">
                                </div>
                            </div>
                            <div class="col-lg-3  col-md-3">
                                <div class="blog_info text-right">
                                    <ul class="blog_meta list">
                                        <li>{{ artwork.seller }}<i class="lnr lnr-user"></i></li><br>
                                        <li>{{ auction.endDate }}<i class="lnr lnr-calendar-full"></i></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-9 col-md-9 blog_details">
                                <h2>{{ artwork.title }}</h2>
                                <br>
                                <h6> Winner : {{ auction.winner.user.username }} </h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% if auction.winner.user.id == user.id %}
        <div class="comment-form">
            <h4>Fill This Form To Get Order Details</h4>
            <form method="POST" action="/sendWinnerEmail/{{ artwork.seller.user.id }}/">
                {% csrf_token %}
                <div class="form-group form-inline">
                    <div class="form-group col-lg-6 col-md-6 name">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name" onfocus="this.placeholder = ''"
                            onblur="this.placeholder = 'Enter Name'">
                    </div>
                    <div class="form-group col-lg-6 col-md-6 email">
                        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email address"
                            onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
                    </div>
                </div>
                <input type="hidden" name="title" value="{{ artwork.title }}"/>
                <div class="col-md-12 form-group">
                    <button type="submit" value="submit" class="primary-btn">Submit</button>
                </div>
            </form>
        </div>          
        {% endif %}
        
{% endblock %}

templates/browseArt.html
{% extends 'master.html' %}
{% block body %}
    	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Artworks</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'index' %}">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="#">Artworks</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->
	{% include 'messages.html' %}
    {% block content %}
    {% endblock %}
    <br><br><br>
	<!-- start product Area -->
		<!-- single product slide -->
		<div class="single-product-slider">
			<div class="container">
				<div class="row">

					<!-- single product -->
                    {% for art in artwork %}
					<div class="col-lg-3 col-md-6">
						<div class="single-product">
							<img class="img-fluid" src="{{ art.aimg.url }}" alt="">
							<div class="product-details">
								<h6>{{ art.title }}</h6>
								<div class="price">
									<h6>{{ art.category }}</h6>
								</div>
                                <div class="price">
									<p>By {{ art.seller.user.username }}</p>
								</div>
                                <div class="price">
                                    {% if art.artworkStatus %}
									    <p style="color:green;">Available</p>
                                    {% else %}
                                        <p style="color:red;">Sold</p>
                                    {% endif %}
								</div>
								<div class="prd-bottom">
									<a href="{% url 'bidArt' id=art.id %}" class="social-info">
										<span class="ti-bag"></span>
										<p class="hover-text">Bid</p>
									</a>
									<a href="{% url 'artworkDetail' id=art.id %}" class="social-info">
										<span class="lnr lnr-move"></span>
										<p class="hover-text">View More</p>
									</a>
								</div>
							</div>
						</div>
					</div>
                    {% endfor %}
				</div>
			</div>
		</div>
	<!-- end product Area -->
{% endblock %}

templates/editAuction.html
{% extends 'masterSeller.html' %}
{% block body %}
		<!-- Start Banner Area -->
		<section class="banner-area organic-breadcrumb">
			<div class="container">
				<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
					<div class="col-first">
						<h1>Edit Auction</h1>
						<nav class="d-flex align-items-center">
							<a href="{% url 'indexSeller' %}">Home<span class="lnr lnr-arrow-right"></span></a>
						</nav>
					</div>
				</div>
			</div>
		</section>
		<!-- End Banner Area -->
        <!--================Login Box Area =================-->
		<section class="login_box_area section_gap">
			<div class="container">
				<div class="row">
					<div class="col-lg-6">
						<div class="login_box_img">
							<img class="img-fluid" src="/static/img/auction-form.jpg" alt="">
							<div class="hover">
								<h4>Edit Auction</h4>
							</div>
						</div>
					</div>
					<div class="col-lg-6">
						<div class="login_form_inner">
							<h3>Edit Auction</h3>
							<form class="row login_form" action="{% url 'editAuction' id=auction.id %}" method="POST">
								{% csrf_token %}
                                {{ form.as_p }}
                                <div class="col-md-12 form-group">
                                    <button type="submit" value="submit" class="primary-btn">Save Changes</button>
                                </div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</section>
	<!--================End Login Box Area =================-->
    {% endblock %}

templates/editBid.html
{% extends 'master.html' %}
{% block body %}
    	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Edit Bid</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'index' %}">Home<span class="lnr lnr-arrow-right"></span></a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->
    <!--================Login Box Area =================-->
        <section class="login_box_area section_gap">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="login_box_img">
                            <img class="img-fluid" src="/static/img/auction.jpg" alt="">
                            <div class="hover">
                                <h4>Edit Bid</h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="login_form_inner">
                            <h3>Edit Bid</h3>
                            <form class="row login_form" action="{% url 'editBid' id=bid.id %}" method="POST">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <div class="col-md-12 form-group">
                                    <button type="submit" value="submit" class="primary-btn">Apply Changes</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <!--================End Login Box Area =================-->
{% endblock %}

templates/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}